sudo: false
language: python
cache:
  directories:
    - .hypothesis
python:
  - "2.6"
  - "2.7"
  - "3.4"
install: 
    - pip install -r requirements.txt
    - pip install -r tests/requirements-dev.txt
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install robotframework-python3; else pip install robotframework; fi
    - python setup.py install
before_script:
    - chmod -x tests/test_*.py
    - export PATH=$PATH:$PWD/bin
script: 
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then nosetests --with-coverage --cover-erase --cover-package=biotest -a '!py27+'; else nosetests --with-coverage --cover-erase --cover-package=biotest; fi 
after_success:
    - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/733ce26f5af2ec9f2503
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
